### ISSUE TITLE
suspicious comparison in engine/peer.go

### ISSUE THREAD

**Issue by josharian** [MixinNetwork/kraken#1]
https://github.com/MixinNetwork/kraken/blob/221733d5bf764c9a1c6da5df61ee2937581b1dd1/engine/peer.go#L336

Should this be `next+uint32(gap) > 65535` instead of `> 65536`?

**Comment by cedricfung** [comment]
I agree 👍 

this repo is really a mess, no docs, no tests yet.

**Comment by josharian** [comment]
I'm still learning things from reading the code, though. :) Not that I would object to docs or tests, of course.

**Comment by cedricfung** [comment]
Docs will be ready within 24 hours. Feel free to submit issues and PR.

Thank you
