### ISSUE TITLE
Is it possible to change opus bandwidth a little lower than 48000?

### ISSUE THREAD

**Issue by Leddly** [MixinNetwork/kraken#10]
Hi, Cedric.

After I checked the kraken system perfectly working on ec2 env, I found kraken using the opus codec and the setting has 48000 bandwidth.

But, that means to me, even if I send just a bit of data stream, there is sort of waste of data on time, I think.

Is it possible to change opus bandwidth a little lower than 48000?

Thank you again, Cedric.

**Comment by cedricfung** [comment]
48000 is the sample rate, and I think WebRTC enforces the value.

**Comment by Leddly** [comment]
@cedricfung 
Much appreciated for your reply, Cedric :)
