### ISSUE TITLE
Possibility of memory leak?

### ISSUE THREAD

**Issue by Leddly** [MixinNetwork/kraken#12]
When someone get connected and disconnected to the kraken server, the occupied memory usage seems still consuming the resources.

Is it due to nginx' cache problem or just time-consuming work to flush allocated memory?

**Comment by cedricfung** [comment]
Haven't detected obvious memory leaks yet. I learnt something https://vec.io/posts/golang-and-memory

**Comment by Leddly** [comment]
@cedricfung 
Sorry for late comment, Cedric. I read the info on your comment and I think I have the point. Quite make sense what you explained on your post :D
Many thanks!!
