### ISSUE TITLE
OnTrackTimeout

### ISSUE THREAD

**Issue by chinarui-na** [MixinNetwork/kraken#13]
ice can not connect

**Comment by cedricfung** [comment]
It is mostly configuration issue. Please follow discussions in this issue https://github.com/MixinNetwork/kraken/issues/5

**Comment by chinarui-na** [comment]
my server config is 
[engine]
# the network interface to bind
interface = "eth0"
# the IP address to bind, empty allows the engine to get it from interface
address = "172.16.3.221"
log-level = 10
# the UDP port range, leave them to 0 for default strategy
port-min = 0
port-max = 0

[turn]
host = "turn:turn.kraken.fm:443"
# must be identical to coturn static auth secret
secret = "812ecb0604d9b90c4aa43a0e3fd1ba85"

[rpc]
port = 7000


index.js config is 

var res = await rpc('turn', [unameRPC]);
      // if (ICE_POLICY === 'relay' && res.data && res.data.length > 0) {
      //   configuration.iceServers = res.data;
      //   configuration.iceTransportPolicy = 'relay';
      // } else {
      //   configuration.iceServers = [];
      //   configuration.iceTransportPolicy = 'all';
      // }
      configuration.iceServers = [];
      configuration.iceTransportPolicy = 'all';
another config is needed?

**Comment by chinarui-na** [comment]
server config is 
[engine]
interface = "eth0"
address = "172.16.3.221"
log-level = 10
port-min = 0
port-max = 0
[turn]
host = "turn:turn.kraken.fm:443"
secret = "812ecb0604d9b90c4aa43a0e3fd1ba85"

[rpc]
port = 7000

index.js 
var res = await rpc('turn', [unameRPC]);
      // if (ICE_POLICY === 'relay' && res.data && res.data.length > 0) {
      //   configuration.iceServers = res.data;
      //   configuration.iceTransportPolicy = 'relay';
      // } else {
      //   configuration.iceServers = [];
      //   configuration.iceTransportPolicy = 'all';
      // }
      configuration.iceServers = [];
      configuration.iceTransportPolicy = 'all';

another config is needed?
