### ISSUE TITLE
NACK (question)

### ISSUE THREAD

**Issue by ldenoue** [MixinNetwork/kraken#19]
In Sean Dubois's broadcast example https://github.com/pion/webrtc/blob/master/examples/broadcast/main.go#L137 there's a loop to constantly read the sender (after AddTrack) using rtcpBuf := make([]byte, 1500)

Why don't we need to do the same with Kraken?
Is it because it's done somewhere else, like in the interceptor.Registry in router.go?

**Comment by cedricfung** [comment]
We have that in old code, after upgraded to pion v3, the nack interceptor just does the work.

**Comment by cedricfung** [comment]
https://github.com/MixinNetwork/kraken/commit/a40dd99228f313e3fc433534ea0b5f9e011dbc5d
