### ISSUE TITLE
Try to set up kraken api server with nginx on local environment 

### ISSUE THREAD

**Issue by Leddly** [MixinNetwork/kraken#9]
![index_html](https://user-images.githubusercontent.com/43400928/93181021-e6e01900-f772-11ea-986a-971b75e16026.png)

I
![turn_server](https://user-images.githubusercontent.com/43400928/93181241-30c8ff00-f773-11ea-8165-feb2ce855306.png)

I've been struggling with local kraken api with nginx and turn server setting-up

Whatever you need to resolve this situation, please leave any comment.

Thanks for reading it.

**Comment by cedricfung** [comment]
Hi, have you tried suggestions in this issue https://github.com/MixinNetwork/kraken/issues/5#issuecomment-686243317

Indeed, there is no need to run a turn server for a local deployment.

**Comment by Leddly** [comment]
@cedricfung 
Thanks for your comment, Cedric.
I think I wrote something wrong on the issue. I mean local is on ec2 env and the kraken api server and turn server are not on the same vm server.
And plus, I added nginx server just front of kraken api server. Dose it affect on this malfunctioning issue?

**Comment by cedricfung** [comment]
What's your configuration of kraken, turn server, the kraken.fm index.js and your nginx?

**Comment by Leddly** [comment]
[config/engine.toml]

[engine]
#the network interface to bind
interface = "ens5"
#the IP address to bind, empty allows the engine to get it from interface
address = "127.0.0.1"
log-level = 7
#the UDP port range, leave them to 0 for default strategy
port-min = 49152
port-max = 65535

[turn]
host = "turn:[ec2-server]:3478"
#must be identical to coturn static auth secret
secret = "openssl-generated-key"

[rpc]
port = 7000

---------------------------------------------------------------------------------------------------

[Turnserver]

listening-port=3478
external-ip=[public-ip]
listening-ip=[ec2-ip]
server-name=[domain]
fingerprint
lt-cred-mech
realm=rtcdev1.com
log-file=/var/log/turn.log
simple-log
verbose
no-stun
proc-user=turnserver
proc-group=turnserver
no-multicast-peers
no-loopback-peerp
use-auth-secret
static-auth-secret=[openssl-generated-key]



------------------------------------------------------------------------------------------------------
[Nginx]


upstream kraken_server {
    server 127.0.0.1:7000 fail_timeout=0;
}

map $http_upgrade $connection_upgrade {
     default upgrade;
     ''      close;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name [kraken_domain];

    ssl_certificate /home/ubuntu/ssl/[crt];
    ssl_certificate_key /home/ubuntu/ssl/[key];

    # Disable SSL. use TLS
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    # Optimise cipher suits
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;

    # Enable HSTS
    add_header Strict-Transport-Security "max-age=31536000" always;

    # SSL sessions
    ssl_session_cache shared:SSL:40m;
    ssl_session_timeout 4h;
    ssl_session_tickets on;

    charset utf-8;
    client_max_body_size 128M;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://kraken_server;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 86400s;
    }
}

And I only changed some parts of index.js

const KRAKEN_API = 'https://[kraken-api-server]';
const TURNSERVER = 'turn:[turnserver]:3478'

const configuration = {
        iceServers: [{
            urls: TURNSERVER,
            username: "webrtc",
            credential: "[openssl-generated-key]"
        }],


These are what I have made for setting-up

**Comment by cedricfung** [comment]
I think your engine.address is the issue, you make kraken bind to 127.0.0.1 so that the turn server can't connect with it.

**Comment by Leddly** [comment]
ubuntu@ip:/tmp/kraken$ ./kraken -c config/engine.toml -s engine
2020/09/15 08:44:39 Setup(config/engine.toml)
2020/09/15 08:44:39 BuildEngine(IP: [server_ip], Interface: ens5, Ports: 49152-65535)
2020/09/15 08:44:39 ServeRPC(:8080)
2020/09/15 08:44:39 RPC.handle(id: baaf7af0-a683-4fdc-a62f-e4cd174d849a, method: subscribe, params: [index.html 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D b45a7cb3-0d35-4a4c-9c1d-eadfc593a038])
2020/09/15 08:44:39 RPC.handle(id: baaf7af0-a683-4fdc-a62f-e4cd174d849a, time: 0.000113s) ERROR {"status":202,"code":5002001,"description":"peer 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D not found in index.html"}
2020/09/15 08:44:39 RPC.handle(id: 6f0122ad-c38f-4d94-96d2-4412c6eaca98, method: subscribe, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D 77ae18ea-4c7d-4be7-9abc-100810ecebff])
2020/09/15 08:44:39 RPC.handle(id: 6f0122ad-c38f-4d94-96d2-4412c6eaca98, time: 0.000031s) ERROR {"status":202,"code":5002001,"description":"peer 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D not found in index.html"}
2020/09/15 08:44:42 RPC.handle(id: b334c6ec-02af-4be8-810f-5e5df99dfb03, method: subscribe, params: [index.html 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D b45a7cb3-0d35-4a4c-9c1d-eadfc593a038])
2020/09/15 08:44:42 RPC.handle(id: b334c6ec-02af-4be8-810f-5e5df99dfb03, time: 0.000070s) ERROR {"status":202,"code":5002001,"description":"peer 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D not found in index.html"}
2020/09/15 08:44:42 RPC.handle(id: 41c55a8f-1019-422d-9b43-4b59723af102, method: subscribe, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D 77ae18ea-4c7d-4be7-9abc-100810ecebff])
2020/09/15 08:44:42 RPC.handle(id: 41c55a8f-1019-422d-9b43-4b59723af102, time: 0.000045s) ERROR {"status":202,"code":5002001,"description":"peer 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D not found in index.html"}
2020/09/15 08:44:45 RPC.handle(id: 62f8d2fb-0172-4d74-bd8b-34eb2a4f4b5a, method: publish, params: [index.html 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D {"type":"offer","sdp":"v=0\r\no=- 7392297118507819032 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS 46GV9tvWKto9COu8JCKpyEK4AeXVX5XkCwaZ\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:n18i\r\na=ice-pwd:W0GHwqyNZxKsW/RELV6FX5Hz\r\na=ice-options:trickle\r\na=fingerprint:sha-256 25:8C:93:DE:65:50:5D:F2:5D:04:A8:99:49:5A:33:6C:D9:D2:B9:E6:F1:A3:31:29:CE:07:CC:56:83:3D:D5:59\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:46GV9tvWKto9COu8JCKpyEK4AeXVX5XkCwaZ 4d071aa5-e15e-4ce0-a2e5-f31412c0bd94\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:323781343 cname:I1wE9X72sh+FWXwT\r\na=ssrc:323781343 msid:46GV9tvWKto9COu8JCKpyEK4AeXVX5XkCwaZ 4d071aa5-e15e-4ce0-a2e5-f31412c0bd94\r\na=ssrc:323781343 mslabel:46GV9tvWKto9COu8JCKpyEK4AeXVX5XkCwaZ\r\na=ssrc:323781343 label:4d071aa5-e15e-4ce0-a2e5-f31412c0bd94\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:n18i\r\na=ice-pwd:W0GHwqyNZxKsW/RELV6FX5Hz\r\na=ice-options:trickle\r\na=fingerprint:sha-256 25:8C:93:DE:65:50:5D:F2:5D:04:A8:99:49:5A:33:6C:D9:D2:B9:E6:F1:A3:31:29:CE:07:CC:56:83:3D:D5:59\r\na=setup:actpass\r\na=mid:1\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}])
2020/09/15 08:44:45 HandlePeer(index.html:3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D:1525ef44-9e9f-42e0-a692-af9371c07fa4) OnSignalingStateChange(have-remote-offer)
2020/09/15 08:44:45 HandlePeer(index.html:3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D:1525ef44-9e9f-42e0-a692-af9371c07fa4) OnICEConnectionStateChange(checking)
2020/09/15 08:44:45 HandlePeer(index.html:3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D:1525ef44-9e9f-42e0-a692-af9371c07fa4) OnSignalingStateChange(stable)
2020/09/15 08:44:45 RPC.handle(id: 62f8d2fb-0172-4d74-bd8b-34eb2a4f4b5a, time: 0.009735s) OK
2020/09/15 08:44:45 RPC.handle(id: 3d66caf2-0de2-4c4a-bb52-11f81976da01, method: subscribe, params: [index.html 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D 1525ef44-9e9f-42e0-a692-af9371c07fa4])
2020/09/15 08:44:45 RPC.handle(id: 3d66caf2-0de2-4c4a-bb52-11f81976da01, time: 0.000098s) OK
2020/09/15 08:44:45 RPC.handle(id: f2fd3782-8b53-4854-a45e-33046de28628, method: subscribe, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D 77ae18ea-4c7d-4be7-9abc-100810ecebff])
2020/09/15 08:44:45 RPC.handle(id: f2fd3782-8b53-4854-a45e-33046de28628, time: 0.000038s) ERROR {"status":202,"code":5002001,"description":"peer 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D not found in index.html"}
2020/09/15 08:44:46 RPC.handle(id: 01e5f902-cafe-49c2-8fb0-32ee63d214b5, method: publish, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D {"type":"offer","sdp":"v=0\r\no=- 7045118477954453490 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS ASY1Ca1leZujkKpUtIiode4FqSREWk8seI2A\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:02xH\r\na=ice-pwd:vLztqxp/QLnbKbIr/15Dw1BX\r\na=ice-options:trickle\r\na=fingerprint:sha-256 BF:31:46:28:95:CB:AA:85:D6:B4:E2:16:D0:EA:B0:D8:CA:11:6B:BE:7E:41:7C:57:F3:36:21:A8:E9:AB:EB:9A\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:ASY1Ca1leZujkKpUtIiode4FqSREWk8seI2A 99fbbd4a-9ca5-4ef3-86cc-67edb8debfa5\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:965944017 cname:xGoeZal6qbvZRoCf\r\na=ssrc:965944017 msid:ASY1Ca1leZujkKpUtIiode4FqSREWk8seI2A 99fbbd4a-9ca5-4ef3-86cc-67edb8debfa5\r\na=ssrc:965944017 mslabel:ASY1Ca1leZujkKpUtIiode4FqSREWk8seI2A\r\na=ssrc:965944017 label:99fbbd4a-9ca5-4ef3-86cc-67edb8debfa5\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:02xH\r\na=ice-pwd:vLztqxp/QLnbKbIr/15Dw1BX\r\na=ice-options:trickle\r\na=fingerprint:sha-256 BF:31:46:28:95:CB:AA:85:D6:B4:E2:16:D0:EA:B0:D8:CA:11:6B:BE:7E:41:7C:57:F3:36:21:A8:E9:AB:EB:9A\r\na=setup:actpass\r\na=mid:1\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}])
2020/09/15 08:44:46 HandlePeer(index.html:07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D:98c8d588-c8c8-4351-95c9-b9cb0b72112a) OnSignalingStateChange(have-remote-offer)
2020/09/15 08:44:46 HandlePeer(index.html:07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D:98c8d588-c8c8-4351-95c9-b9cb0b72112a) OnSignalingStateChange(stable)
2020/09/15 08:44:46 HandlePeer(index.html:07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D:98c8d588-c8c8-4351-95c9-b9cb0b72112a) OnICEConnectionStateChange(checking)
2020/09/15 08:44:46 RPC.handle(id: 01e5f902-cafe-49c2-8fb0-32ee63d214b5, time: 0.001546s) OK
2020/09/15 08:44:46 RPC.handle(id: 089704c2-1829-40d4-89eb-017ee2f5d3ca, method: subscribe, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D 98c8d588-c8c8-4351-95c9-b9cb0b72112a])
2020/09/15 08:44:46 RPC.handle(id: 089704c2-1829-40d4-89eb-017ee2f5d3ca, time: 0.000086s) OK
2020/09/15 08:44:48 RPC.handle(id: 31b09ddc-9725-4487-af02-2a76cf59042a, method: subscribe, params: [index.html 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D 1525ef44-9e9f-42e0-a692-af9371c07fa4])
2020/09/15 08:44:48 RPC.handle(id: 31b09ddc-9725-4487-af02-2a76cf59042a, time: 0.000069s) OK
2020/09/15 08:44:49 RPC.handle(id: beda91d2-42f5-4afb-8f3d-d6d188339db7, method: subscribe, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D 98c8d588-c8c8-4351-95c9-b9cb0b72112a])
2020/09/15 08:44:49 RPC.handle(id: beda91d2-42f5-4afb-8f3d-d6d188339db7, time: 0.000079s) OK
2020/09/15 08:44:51 RPC.handle(id: b1c4f795-8f2e-4a18-8f3d-cbea3a64b190, method: subscribe, params: [index.html 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D 1525ef44-9e9f-42e0-a692-af9371c07fa4])
2020/09/15 08:44:51 RPC.handle(id: b1c4f795-8f2e-4a18-8f3d-cbea3a64b190, time: 0.000099s) OK
2020/09/15 08:44:52 RPC.handle(id: 80e36603-d5e1-4acf-802a-cd12e918b5a3, method: subscribe, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D 98c8d588-c8c8-4351-95c9-b9cb0b72112a])
2020/09/15 08:44:52 RPC.handle(id: 80e36603-d5e1-4acf-802a-cd12e918b5a3, time: 0.000096s) OK
2020/09/15 08:44:54 RPC.handle(id: fea3df03-a40b-4cfe-8da6-a412cbd4fbb4, method: subscribe, params: [index.html 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D 1525ef44-9e9f-42e0-a692-af9371c07fa4])
2020/09/15 08:44:54 RPC.handle(id: fea3df03-a40b-4cfe-8da6-a412cbd4fbb4, time: 0.000088s) OK
2020/09/15 08:44:55 RPC.handle(id: edc13646-6f7a-4435-8e76-30a54a7fb081, method: subscribe, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D 98c8d588-c8c8-4351-95c9-b9cb0b72112a])
2020/09/15 08:44:55 RPC.handle(id: edc13646-6f7a-4435-8e76-30a54a7fb081, time: 0.000073s) OK
2020/09/15 08:44:55 HandlePeer(index.html:3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D:1525ef44-9e9f-42e0-a692-af9371c07fa4) OnTrackTimeout()
2020/09/15 08:44:55 PeerClose(index.html:3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D:1525ef44-9e9f-42e0-a692-af9371c07fa4) now
2020/09/15 08:44:55 PeerClose(index.html:3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D:CLOSED) with <nil>
2020/09/15 08:44:55 HandlePeer(index.html:3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D:CLOSED) OnConnectionStateChange(closed)
2020/09/15 08:44:55 HandlePeer(index.html:3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D:CLOSED) OnICEConnectionStateChange(closed)
2020/09/15 08:44:56 HandlePeer(index.html:07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D:98c8d588-c8c8-4351-95c9-b9cb0b72112a) OnTrackTimeout()
2020/09/15 08:44:56 PeerClose(index.html:07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D:98c8d588-c8c8-4351-95c9-b9cb0b72112a) now
2020/09/15 08:44:56 PeerClose(index.html:07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D:CLOSED) with <nil>
2020/09/15 08:44:56 HandlePeer(index.html:07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D:CLOSED) OnConnectionStateChange(closed)
2020/09/15 08:44:56 HandlePeer(index.html:07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D:CLOSED) OnICEConnectionStateChange(closed)
2020/09/15 08:44:57 RPC.handle(id: 2a69efcc-084a-425e-80ae-001995a81c2f, method: subscribe, params: [index.html 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D 1525ef44-9e9f-42e0-a692-af9371c07fa4])
2020/09/15 08:44:57 RPC.handle(id: 2a69efcc-084a-425e-80ae-001995a81c2f, time: 0.000147s) ERROR {"status":202,"code":5002002,"description":"peer 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D closed in index.html"}
2020/09/15 08:44:58 RPC.handle(id: 5d0c99b5-62d7-44e5-bed4-1f2d2632f94b, method: subscribe, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D 98c8d588-c8c8-4351-95c9-b9cb0b72112a])
2020/09/15 08:44:58 RPC.handle(id: 5d0c99b5-62d7-44e5-bed4-1f2d2632f94b, time: 0.000127s) ERROR {"status":202,"code":5002002,"description":"peer 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D closed in index.html"}
2020/09/15 08:45:00 RPC.handle(id: f52791de-08f6-41aa-aeeb-d9010d48605f, method: subscribe, params: [index.html 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D 1525ef44-9e9f-42e0-a692-af9371c07fa4])
2020/09/15 08:45:00 RPC.handle(id: f52791de-08f6-41aa-aeeb-d9010d48605f, time: 0.000132s) ERROR {"status":202,"code":5002002,"description":"peer 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D closed in index.html"}
2020/09/15 08:45:01 RPC.handle(id: c9225f70-14b5-46c4-9cdf-03549dea405e, method: subscribe, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D 98c8d588-c8c8-4351-95c9-b9cb0b72112a])
2020/09/15 08:45:01 RPC.handle(id: c9225f70-14b5-46c4-9cdf-03549dea405e, time: 0.000046s) ERROR {"status":202,"code":5002002,"description":"peer 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D closed in index.html"}
2020/09/15 08:45:04 RPC.handle(id: b02240d7-265c-43af-9842-4921423588ff, method: subscribe, params: [index.html 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D 1525ef44-9e9f-42e0-a692-af9371c07fa4])
2020/09/15 08:45:04 RPC.handle(id: b02240d7-265c-43af-9842-4921423588ff, time: 0.000066s) ERROR {"status":202,"code":5002002,"description":"peer 3fe6eaf2-3176-4592-9f1d-5e95ad470035%3Ac2ZkZ3NmZGdmZA%3D%3D closed in index.html"}
2020/09/15 08:45:04 RPC.handle(id: 7c1059d5-25aa-48aa-ae9f-e6f884b445ac, method: subscribe, params: [index.html 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D 98c8d588-c8c8-4351-95c9-b9cb0b72112a])
2020/09/15 08:45:04 RPC.handle(id: 7c1059d5-25aa-48aa-ae9f-e6f884b445ac, time: 0.000068s) ERROR {"status":202,"code":5002002,"description":"peer 07e0bc5c-6488-4620-816d-33898497455e%3ANTQ2MzQ1NDM%3D closed in index.html"}

still it's not working and same error log come out as before.
What could be possibly wrong in this system? 

![image](https://user-images.githubusercontent.com/43400928/93188750-5575a480-f77c-11ea-8ba2-ed48dee8c7e1.png)

**Comment by cedricfung** [comment]
There is no problem in this deployment, we use it the same as yours.

I found another issue is the turn server configuration, a bit complicated, let me make some improvements in the kraken.fm code at first.

**Comment by Leddly** [comment]
@cedricfung 
Much appreciated for your help! :D

**Comment by cedricfung** [comment]
Please try the latest kraken.fm code.

**Comment by Leddly** [comment]
@cedricfung 
Wondeful!!! It is perfectly working now.
Nginx, Turn server and Kraken API, all 100% working. Thanks Cedric :))
